// fait-mono/apps/fait-coop/src/components/ui/Input.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

// Define props
const props = defineProps({
  modelValue: {
    type: [String, Number],
    default: ''
  },
  type: {
    type: String,
    default: 'text'
  },
  placeholder: {
    type: String,
    default: ''
  },
  label: {
    type: String,
    default: ''
  },
  helperText: {
    type: String,
    default: ''
  },
  error: {
    type: String,
    default: ''
  },
  disabled: {
    type: Boolean,
    default: false
  },
  required: {
    type: Boolean,
    default: false
  },
  fullWidth: {
    type: Boolean,
    default: false
  },
  id: {
    type: String,
    default: () => `input-${Math.random().toString(36).substring(2, 9)}`
  }
})

// Define emits
const emit = defineEmits(['update:modelValue', 'focus', 'blur', 'input'])

// Generate unique ID if not provided
const inputId = ref(props.id)

// Compute input classes
const inputClasses = computed(() => {
  const classes = [
    'form-input',
    'block',
    'px-3',
    'py-2',
    'border',
    'rounded-md',
    'shadow-sm',
    'placeholder-neutral-400',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-primary-500',
    'focus:border-primary-500',
    'sm:text-sm'
  ]
  
  if (props.error) {
    classes.push('border-red-300')
    classes.push('text-red-900')
    classes.push('focus:ring-red-500')
    classes.push('focus:border-red-500')
  } else {
    classes.push('border-neutral-300')
    classes.push('text-neutral-900')
  }
  
  if (props.disabled) {
    classes.push('bg-neutral-100')
    classes.push('cursor-not-allowed')
  }
  
  if (props.fullWidth) {
    classes.push('w-full')
  }
  
  return classes.join(' ')
})

// Handle input events
const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
  emit('input', event)
}

const handleFocus = (event: Event) => {
  emit('focus', event)
}

const handleBlur = (event: Event) => {
  emit('blur', event)
}
</script>

<template>
  <div :class="{ 'w-full': fullWidth }">
    <label v-if="label" :for="inputId" class="block text-sm font-medium text-neutral-700 mb-1">
      {{ label }}
      <span v-if="required" class="text-red-500">*</span>
    </label>
    
    <input
      :id="inputId"
      :type="type"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :required="required"
      :class="inputClasses"
      @input="handleInput"
      @focus="handleFocus"
      @blur="handleBlur"
    />
    
    <p v-if="error" class="mt-1 text-sm text-red-600">{{ error }}</p>
    <p v-else-if="helperText" class="mt-1 text-sm text-neutral-500">{{ helperText }}</p>
  </div>
</template>

// src/components/ui/form/Input.tsx
import React from 'react';
import classNames from 'classnames';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  className?: string;
  inputClassName?: string;
  labelClassName?: string;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ 
    label, 
    error, 
    helperText, 
    leftIcon, 
    rightIcon, 
    className = '', 
    inputClassName = '',
    labelClassName = '',
    id,
    ...props 
  }, ref) => {
    const inputId = id || `input-${Math.random().toString(36).substring(2, 9)}`;
    
    return (
      <div className={classNames('space-y-1', className)}>
        {label && (
          <label 
            htmlFor={inputId} 
            className={classNames(
              'block text-sm font-medium text-gray-700',
              error ? 'text-red-500' : '',
              labelClassName
            )}
          >
            {label}
          </label>
        )}
        <div className="relative rounded-md shadow-sm">
          {leftIcon && (
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              {leftIcon}
            </div>
          )}
          <input
            id={inputId}
            className={classNames(
              'block w-full rounded-md shadow-sm',
              error 
                ? 'border-red-300 text-red-900 placeholder-red-300 focus:border-red-500 focus:ring-red-500' 
                : 'border-gray-300 focus:border-primary-500 focus:ring-primary-500',
              leftIcon ? 'pl-10' : '',
              rightIcon ? 'pr-10' : '',
              inputClassName
            )}
            aria-invalid={!!error}
            aria-describedby={
              error 
                ? `${inputId}-error` 
                : helperText 
                  ? `${inputId}-description` 
                  : undefined
            }
            ref={ref}
            {...props}
          />
          {rightIcon && (
            <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
              {rightIcon}
            </div>
          )}
        </div>
        {error && (
          <p className="mt-1 text-sm text-red-600" id={`${inputId}-error`}>
            {error}
          </p>
        )}
        {helperText && !error && (
          <p className="mt-1 text-sm text-gray-500" id={`${inputId}-description`}>
            {helperText}
          </p>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';

export default Input;
