// src/routes/booking/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { auth } from '$lib/stores/auth';
	import Button from '$lib/components/ui/Button.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import LoginSignupModal from '$lib/components/auth/LoginSignupModal.svelte';

	let selectedService = '';
	let isLoading = false;
	let error: string | null = null;
	let isSubmitting = false;
	let showLoginModal = false;

	// Form data
	let selectedDate = '';
	let selectedTime = '';
	let address = '';
	let zipCode = '';
	let notes = '';
	let formErrors: Record<string, string> = {};

	// Available time slots
	const timeSlots = [
		'08:00', '09:00', '10:00', '11:00', '12:00',
		'13:00', '14:00', '15:00', '16:00', '17:00'
	];

	// Get today's date for min date validation
	const today = new Date().toISOString().split('T')[0];

	// Service options
	const services = [
		{ id: 'plumbing', name: 'Plumbing Services', price: '$85-125/hr + service call', description: 'Leak repairs, drain cleaning, fixture installation, pipe repairs, water heater service' },
		{ id: 'electrical', name: 'Electrical Services', price: '$75-125/hr + service call', description: 'Outlet installation, light fixtures, ceiling fans, electrical panel upgrades, troubleshooting' },
		{ id: 'cleaning', name: 'House Cleaning', price: '$80-150', description: 'Professional deep cleaning for your entire home including kitchens, bathrooms, bedrooms, and living areas' },
		{ id: 'handyman', name: 'Handyman Services', price: '$45-75/hr', description: 'General repairs, installations, maintenance, furniture assembly, minor electrical work' },
		{ id: 'gardening', name: 'Gardening & Landscaping', price: '$40-80/hr', description: 'Lawn care, landscaping, garden maintenance, seasonal cleanup, plant care' },
		{ id: 'moving', name: 'Moving Services', price: '$100+/hr', description: 'Professional moving services, packing, loading, transportation, and unpacking' }
	];

	onMount(() => {
		// Check if a service was pre-selected from URL params
		const serviceParam = $page.url.searchParams.get('service');
		if (serviceParam) {
			selectedService = serviceParam;
		}
	});

	function validateForm() {
		formErrors = {};

		if (!selectedService) {
			formErrors.service = 'Please select a service';
		}

		if (!selectedDate) {
			formErrors.date = 'Date is required';
		}

		if (!selectedTime) {
			formErrors.time = 'Time is required';
		}

		if (!address.trim()) {
			formErrors.address = 'Address is required';
		}

		if (!zipCode.trim()) {
			formErrors.zipCode = 'ZIP code is required';
		}

		return Object.keys(formErrors).length === 0;
	}

	async function handleSubmit() {
		// Check if user is authenticated first
		if (!$auth.isAuthenticated) {
			showLoginModal = true;
			return;
		}

		if (!validateForm()) {
			return;
		}

		isSubmitting = true;
		error = null;

		try {
			// Mock booking submission - in real app this would call an API
			await new Promise(resolve => setTimeout(resolve, 1000));

			// Navigate to bookings page with success message
			goto('/bookings?success=true');
		} catch (err) {
			error = 'Failed to create booking. Please try again.';
		} finally {
			isSubmitting = false;
		}
	}

	function handleLoginSuccess() {
		showLoginModal = false;
		// After successful login, automatically submit the form if it's valid
		if (validateForm()) {
			handleSubmit();
		}
	}

	function handleLoginClose() {
		showLoginModal = false;
	}

	function formatTime(timeString: string) {
		const [hours, minutes] = timeString.split(':');
		const hour = parseInt(hours, 10);
		const ampm = hour >= 12 ? 'PM' : 'AM';
		const hour12 = hour % 12 || 12;
		return `${hour12}:${minutes} ${ampm}`;
	}

	$: selectedServiceInfo = services.find(s => s.id === selectedService);
</script>

<svelte:head>
	<title>Book a Service - FAIT</title>
	<meta name="description" content="Book professional services with FAIT's trusted professionals." />
</svelte:head>

<section class="bg-gray-50 py-8">
	<div class="container mx-auto px-6 sm:px-8 lg:px-4">
		<div class="max-w-4xl mx-auto">
			<!-- Header -->
			<div class="text-center mb-8">
				<h1 class="text-4xl font-bold text-gray-900 mb-4">Book a Service</h1>
				<p class="text-xl text-gray-600">Connect with trusted professionals for your home and business needs</p>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
				<!-- Service Selection & Details -->
				<Card variant="elevated" padding="lg">
					<h2 class="text-2xl font-bold text-gray-900 mb-6">Select Your Service</h2>

					<!-- Service Selection -->
					<div class="mb-6">
						<label for="service" class="block text-sm font-medium text-gray-700 mb-2">
							Service Type
						</label>
						<select
							id="service"
							bind:value={selectedService}
							class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
							class:border-red-500={formErrors.service}
						>
							<option value="">Choose a service...</option>
							{#each services as service}
								<option value={service.id}>{service.name}</option>
							{/each}
						</select>
						{#if formErrors.service}
							<p class="text-red-600 text-sm mt-1">{formErrors.service}</p>
						{/if}
					</div>

					<!-- Selected Service Details -->
					{#if selectedServiceInfo}
						<div class="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
							<h3 class="font-semibold text-blue-900 mb-2">{selectedServiceInfo.name}</h3>
							<p class="text-blue-800 text-sm mb-2">{selectedServiceInfo.description}</p>
							<div class="text-lg font-bold text-blue-600">{selectedServiceInfo.price}</div>
						</div>
					{/if}

					<!-- Service Features -->
					<div class="space-y-3">
						<div class="flex items-center space-x-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
							</svg>
							<span class="text-gray-700">Vetted & Insured Professionals</span>
						</div>
						<div class="flex items-center space-x-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
							</svg>
							<span class="text-gray-700">Same-day & Next-day Availability</span>
						</div>
						<div class="flex items-center space-x-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
							</svg>
							<span class="text-gray-700">Transparent Pricing</span>
						</div>
						<div class="flex items-center space-x-3">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
							</svg>
							<span class="text-gray-700">24/7 Customer Support</span>
						</div>
					</div>
				</Card>

				<!-- Booking Form -->
				<Card variant="elevated" padding="lg">
					<h2 class="text-2xl font-bold text-gray-900 mb-6">Booking Details</h2>

					{#if error}
						<div class="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
							<p class="text-red-700">{error}</p>
						</div>
					{/if}

					<form on:submit|preventDefault={handleSubmit} class="space-y-6">
						<!-- Date Selection -->
						<div>
							<label for="date" class="block text-sm font-medium text-gray-700 mb-2">
								Preferred Date
							</label>
							<input
								type="date"
								id="date"
								bind:value={selectedDate}
								min={today}
								class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								class:border-red-500={formErrors.date}
							/>
							{#if formErrors.date}
								<p class="text-red-600 text-sm mt-1">{formErrors.date}</p>
							{/if}
						</div>

						<!-- Time Selection -->
						<div>
							<label for="time" class="block text-sm font-medium text-gray-700 mb-2">
								Preferred Time
							</label>
							<select
								id="time"
								bind:value={selectedTime}
								class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								class:border-red-500={formErrors.time}
							>
								<option value="">Select a time</option>
								{#each timeSlots as timeSlot}
									<option value={timeSlot}>{formatTime(timeSlot)}</option>
								{/each}
							</select>
							{#if formErrors.time}
								<p class="text-red-600 text-sm mt-1">{formErrors.time}</p>
							{/if}
						</div>

						<!-- Address -->
						<div>
							<label for="address" class="block text-sm font-medium text-gray-700 mb-2">
								Service Address
							</label>
							<input
								type="text"
								id="address"
								bind:value={address}
								placeholder="Enter the service location"
								class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								class:border-red-500={formErrors.address}
							/>
							{#if formErrors.address}
								<p class="text-red-600 text-sm mt-1">{formErrors.address}</p>
							{/if}
						</div>

						<!-- ZIP Code -->
						<div>
							<label for="zipCode" class="block text-sm font-medium text-gray-700 mb-2">
								ZIP Code
							</label>
							<input
								type="text"
								id="zipCode"
								bind:value={zipCode}
								placeholder="Enter ZIP code"
								class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								class:border-red-500={formErrors.zipCode}
							/>
							{#if formErrors.zipCode}
								<p class="text-red-600 text-sm mt-1">{formErrors.zipCode}</p>
							{/if}
						</div>

						<!-- Notes -->
						<div>
							<label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
								Additional Notes (Optional)
							</label>
							<textarea
								id="notes"
								bind:value={notes}
								rows="3"
								placeholder="Any special instructions or requirements..."
								class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
							></textarea>
						</div>

						<!-- Submit Button -->
						<Button
							type="submit"
							variant="primary"
							class="w-full"
							disabled={isSubmitting}
						>
							{#if isSubmitting}
								<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
									<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
									<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
								</svg>
								Booking...
							{:else}
								Book Now
							{/if}
						</Button>
					</form>
				</Card>
			</div>
		</div>
	</div>
</section>

<!-- Login/Signup Modal -->
<LoginSignupModal
	isOpen={showLoginModal}
	on:success={handleLoginSuccess}
	on:close={handleLoginClose}
/>

// fait-mono/apps/fait-coop/src/views/Booking.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import MainLayout from '../components/layout/MainLayout.vue'
import Card from '../components/ui/Card.vue'
import Button from '../components/ui/Button.vue'
import Input from '../components/ui/Input.vue'
import Badge from '../components/ui/Badge.vue'

// Available services
const services = ref([
  {
    id: 1,
    name: 'Home Inspection',
    description: 'Comprehensive inspection of your home to identify potential issues.',
    duration: 120,
    price: 250,
    category: 'inspection'
  },
  {
    id: 2,
    name: 'Plumbing Repair',
    description: 'Fix leaky pipes, clogged drains, and other plumbing issues.',
    duration: 90,
    price: 150,
    category: 'repair'
  },
  {
    id: 3,
    name: 'Electrical Work',
    description: 'Installation and repair of electrical systems and fixtures.',
    duration: 120,
    price: 200,
    category: 'electrical'
  },
  {
    id: 4,
    name: 'HVAC Maintenance',
    description: 'Regular maintenance of heating, ventilation, and air conditioning systems.',
    duration: 60,
    price: 120,
    category: 'maintenance'
  },
  {
    id: 5,
    name: 'Roof Inspection',
    description: 'Thorough inspection of your roof to identify damage or potential issues.',
    duration: 90,
    price: 180,
    category: 'inspection'
  },
  {
    id: 6,
    name: 'Painting Services',
    description: 'Interior and exterior painting services for your home.',
    duration: 240,
    price: 350,
    category: 'renovation'
  }
])

// Form data
const formData = ref({
  service: '',
  date: '',
  time: '',
  name: '',
  email: '',
  phone: '',
  address: '',
  notes: ''
})

// Form errors
const formErrors = ref({
  service: '',
  date: '',
  time: '',
  name: '',
  email: '',
  phone: ''
})

// Form state
const currentStep = ref(1)
const isSubmitting = ref(false)
const isSubmitted = ref(false)

// Available time slots
const timeSlots = ref([
  '9:00 AM', '10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'
])

// Selected service
const selectedService = computed(() => {
  if (!formData.value.service) return null
  return services.value.find(service => service.id.toString() === formData.value.service)
})

// Format price
const formatPrice = (price: number) => {
  return `$${price.toFixed(2)}`
}

// Format duration
const formatDuration = (minutes: number) => {
  const hours = Math.floor(minutes / 60)
  const mins = minutes % 60
  
  if (hours === 0) return `${mins} minutes`
  if (mins === 0) return `${hours} hour${hours > 1 ? 's' : ''}`
  return `${hours} hour${hours > 1 ? 's' : ''} ${mins} minutes`
}

// Go to next step
const nextStep = () => {
  // Validate current step
  if (currentStep.value === 1) {
    formErrors.value.service = !formData.value.service ? 'Please select a service' : ''
    formErrors.value.date = !formData.value.date ? 'Please select a date' : ''
    formErrors.value.time = !formData.value.time ? 'Please select a time' : ''
    
    if (formErrors.value.service || formErrors.value.date || formErrors.value.time) {
      return
    }
  } else if (currentStep.value === 2) {
    formErrors.value.name = !formData.value.name ? 'Please enter your name' : ''
    formErrors.value.email = !formData.value.email ? 'Please enter your email' : ''
    formErrors.value.phone = !formData.value.phone ? 'Please enter your phone number' : ''
    
    if (formErrors.value.name || formErrors.value.email || formErrors.value.phone) {
      return
    }
  }
  
  currentStep.value++
}

// Go to previous step
const prevStep = () => {
  currentStep.value--
}

// Submit booking
const submitBooking = async () => {
  isSubmitting.value = true
  
  try {
    // In a real app, you would send the booking data to a server here
    // For now, we'll just simulate a delay
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    // Show success message
    isSubmitted.value = true
  } catch (error) {
    console.error('Error submitting booking:', error)
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <MainLayout>
    <!-- Hero Section -->
    <section class="py-16 bg-primary-50">
      <div class="container-wide">
        <div class="max-w-3xl mx-auto text-center">
          <h1 class="heading-1 mb-6 text-primary-900">Book a Service</h1>
          <p class="text-body mb-8">
            Schedule a service with one of our trusted professionals. We'll match you with the right person for the job.
          </p>
        </div>
      </div>
    </section>
    
    <!-- Booking Section -->
    <section class="py-16 bg-white">
      <div class="container-wide">
        <div class="max-w-4xl mx-auto">
          <!-- Progress Steps -->
          <div class="mb-8">
            <div class="flex items-center justify-between">
              <div class="flex items-center">
                <div :class="[
                  'flex items-center justify-center w-10 h-10 rounded-full text-white font-medium',
                  currentStep >= 1 ? 'bg-primary-600' : 'bg-neutral-300'
                ]">
                  1
                </div>
                <div class="ml-2">
                  <p :class="[
                    'font-medium',
                    currentStep >= 1 ? 'text-primary-600' : 'text-neutral-500'
                  ]">Select Service</p>
                </div>
              </div>
              
              <div class="flex-1 mx-4 h-1 bg-neutral-200">
                <div :class="[
                  'h-full bg-primary-600 transition-all duration-300',
                  currentStep >= 2 ? 'w-full' : currentStep >= 1 ? 'w-1/2' : 'w-0'
                ]"></div>
              </div>
              
              <div class="flex items-center">
                <div :class="[
                  'flex items-center justify-center w-10 h-10 rounded-full text-white font-medium',
                  currentStep >= 2 ? 'bg-primary-600' : 'bg-neutral-300'
                ]">
                  2
                </div>
                <div class="ml-2">
                  <p :class="[
                    'font-medium',
                    currentStep >= 2 ? 'text-primary-600' : 'text-neutral-500'
                  ]">Your Details</p>
                </div>
              </div>
              
              <div class="flex-1 mx-4 h-1 bg-neutral-200">
                <div :class="[
                  'h-full bg-primary-600 transition-all duration-300',
                  currentStep >= 3 ? 'w-full' : currentStep >= 2 ? 'w-1/2' : 'w-0'
                ]"></div>
              </div>
              
              <div class="flex items-center">
                <div :class="[
                  'flex items-center justify-center w-10 h-10 rounded-full text-white font-medium',
                  currentStep >= 3 ? 'bg-primary-600' : 'bg-neutral-300'
                ]">
                  3
                </div>
                <div class="ml-2">
                  <p :class="[
                    'font-medium',
                    currentStep >= 3 ? 'text-primary-600' : 'text-neutral-500'
                  ]">Confirmation</p>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Success Message -->
          <div v-if="isSubmitted" class="text-center py-8">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-green-500 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h2 class="text-2xl font-bold text-neutral-900 mb-2">Booking Confirmed!</h2>
            <p class="text-neutral-600 mb-6">Your service has been scheduled successfully. We'll send you a confirmation email with all the details.</p>
            <Button to="/" variant="primary">Return to Home</Button>
          </div>
          
          <!-- Booking Form -->
          <Card v-else variant="outline" padding="lg">
            <!-- Step 1: Select Service -->
            <div v-if="currentStep === 1">
              <h2 class="text-2xl font-bold text-neutral-900 mb-6">Select a Service</h2>
              
              <div class="mb-6">
                <label class="block text-sm font-medium text-neutral-700 mb-1">Service Type</label>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div
                    v-for="service in services"
                    :key="service.id"
                    :class="[
                      'border rounded-lg p-4 cursor-pointer transition-all duration-200',
                      formData.service === service.id.toString()
                        ? 'border-primary-500 bg-primary-50'
                        : 'border-neutral-200 hover:border-primary-300'
                    ]"
                    @click="formData.service = service.id.toString()"
                  >
                    <div class="flex justify-between items-start">
                      <div>
                        <h3 class="font-medium text-neutral-900">{{ service.name }}</h3>
                        <p class="text-sm text-neutral-500 mt-1">{{ service.description }}</p>
                        <div class="flex items-center mt-2">
                          <Badge variant="outline" size="sm" class="mr-2">{{ formatDuration(service.duration) }}</Badge>
                          <Badge variant="primary" size="sm">{{ formatPrice(service.price) }}</Badge>
                        </div>
                      </div>
                      <div :class="[
                        'w-5 h-5 rounded-full border flex items-center justify-center',
                        formData.service === service.id.toString()
                          ? 'border-primary-500 bg-primary-500'
                          : 'border-neutral-300'
                      ]">
                        <svg v-if="formData.service === service.id.toString()" xmlns="http://www.w3.org/2000/svg" class="h-3 w-3 text-white" viewBox="0 0 20 20" fill="currentColor">
                          <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
                <p v-if="formErrors.service" class="mt-1 text-sm text-red-600">{{ formErrors.service }}</p>
              </div>
              
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div>
                  <label for="date" class="block text-sm font-medium text-neutral-700 mb-1">Date</label>
                  <input
                    id="date"
                    v-model="formData.date"
                    type="date"
                    :min="new Date().toISOString().split('T')[0]"
                    class="block w-full px-3 py-2 border border-neutral-300 rounded-md shadow-sm focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                  />
                  <p v-if="formErrors.date" class="mt-1 text-sm text-red-600">{{ formErrors.date }}</p>
                </div>
                
                <div>
                  <label class="block text-sm font-medium text-neutral-700 mb-1">Time</label>
                  <div class="grid grid-cols-3 sm:grid-cols-4 gap-2">
                    <button
                      v-for="slot in timeSlots"
                      :key="slot"
                      type="button"
                      :class="[
                        'py-2 px-3 text-sm rounded-md border focus:outline-none',
                        formData.time === slot
                          ? 'bg-primary-50 border-primary-500 text-primary-700'
                          : 'border-neutral-300 text-neutral-700 hover:bg-neutral-50'
                      ]"
                      @click="formData.time = slot"
                    >
                      {{ slot }}
                    </button>
                  </div>
                  <p v-if="formErrors.time" class="mt-1 text-sm text-red-600">{{ formErrors.time }}</p>
                </div>
              </div>
              
              <div class="flex justify-end">
                <Button @click="nextStep" variant="primary">Continue</Button>
              </div>
            </div>
            
            <!-- Step 2: Your Details -->
            <div v-else-if="currentStep === 2">
              <h2 class="text-2xl font-bold text-neutral-900 mb-6">Your Details</h2>
              
              <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <div>
                  <Input
                    v-model="formData.name"
                    label="Full Name"
                    placeholder="Enter your full name"
                    :error="formErrors.name"
                    required
                    fullWidth
                  />
                </div>
                
                <div>
                  <Input
                    v-model="formData.email"
                    type="email"
                    label="Email Address"
                    placeholder="Enter your email"
                    :error="formErrors.email"
                    required
                    fullWidth
                  />
                </div>
                
                <div>
                  <Input
                    v-model="formData.phone"
                    label="Phone Number"
                    placeholder="Enter your phone number"
                    :error="formErrors.phone"
                    required
                    fullWidth
                  />
                </div>
                
                <div>
                  <Input
                    v-model="formData.address"
                    label="Service Address"
                    placeholder="Enter the service address"
                    fullWidth
                  />
                </div>
                
                <div class="sm:col-span-2">
                  <label for="notes" class="block text-sm font-medium text-neutral-700 mb-1">Additional Notes</label>
                  <textarea
                    id="notes"
                    v-model="formData.notes"
                    rows="4"
                    class="block w-full px-3 py-2 border border-neutral-300 rounded-md shadow-sm placeholder-neutral-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="Any specific details or requirements for the service"
                  ></textarea>
                </div>
              </div>
              
              <div class="mt-6 flex justify-between">
                <Button @click="prevStep" variant="outline">Back</Button>
                <Button @click="nextStep" variant="primary">Review Booking</Button>
              </div>
            </div>
            
            <!-- Step 3: Confirmation -->
            <div v-else-if="currentStep === 3">
              <h2 class="text-2xl font-bold text-neutral-900 mb-6">Review Your Booking</h2>
              
              <div class="bg-neutral-50 rounded-lg p-6 mb-6">
                <div class="flex justify-between items-start mb-4">
                  <div>
                    <h3 class="font-semibold text-lg">{{ selectedService?.name }}</h3>
                    <p class="text-neutral-600">{{ selectedService?.description }}</p>
                  </div>
                  <Badge variant="primary">{{ formatPrice(selectedService?.price || 0) }}</Badge>
                </div>
                
                <div class="border-t border-neutral-200 pt-4">
                  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p class="text-sm text-neutral-500">Date</p>
                      <p class="font-medium">{{ formData.date }}</p>
                    </div>
                    <div>
                      <p class="text-sm text-neutral-500">Time</p>
                      <p class="font-medium">{{ formData.time }}</p>
                    </div>
                    <div>
                      <p class="text-sm text-neutral-500">Duration</p>
                      <p class="font-medium">{{ formatDuration(selectedService?.duration || 0) }}</p>
                    </div>
                    <div>
                      <p class="text-sm text-neutral-500">Service Type</p>
                      <p class="font-medium">{{ selectedService?.category }}</p>
                    </div>
                  </div>
                </div>
              </div>
              
              <div class="bg-neutral-50 rounded-lg p-6 mb-6">
                <h3 class="font-semibold mb-4">Contact Information</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <p class="text-sm text-neutral-500">Name</p>
                    <p class="font-medium">{{ formData.name }}</p>
                  </div>
                  <div>
                    <p class="text-sm text-neutral-500">Email</p>
                    <p class="font-medium">{{ formData.email }}</p>
                  </div>
                  <div>
                    <p class="text-sm text-neutral-500">Phone</p>
                    <p class="font-medium">{{ formData.phone }}</p>
                  </div>
                  <div>
                    <p class="text-sm text-neutral-500">Address</p>
                    <p class="font-medium">{{ formData.address || 'Not provided' }}</p>
                  </div>
                </div>
                
                <div v-if="formData.notes" class="mt-4">
                  <p class="text-sm text-neutral-500">Additional Notes</p>
                  <p class="font-medium">{{ formData.notes }}</p>
                </div>
              </div>
              
              <div class="flex items-center mb-6">
                <input id="terms" type="checkbox" class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-neutral-300 rounded" required />
                <label for="terms" class="ml-2 block text-sm text-neutral-700">
                  I agree to the <a href="#" class="text-primary-600 hover:text-primary-500">terms and conditions</a> and <a href="#" class="text-primary-600 hover:text-primary-500">privacy policy</a>.
                </label>
              </div>
              
              <div class="flex justify-between">
                <Button @click="prevStep" variant="outline">Back</Button>
                <Button @click="submitBooking" variant="primary" :loading="isSubmitting" :disabled="isSubmitting">
                  Confirm Booking
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </section>
  </MainLayout>
</template>
