// src/routes/login/+page.svelte
<script>
  import { supabase } from '$lib/supabase.js';
  import { goto } from '$app/navigation';
  import LoadingSpinner from '$lib/components/LoadingSpinner.svelte';
  
  let email = '';
  let password = '';
  let isLoading = false;
  let error = '';
  
  async function handleLogin() {
    if (!email || !password) {
      error = 'Please enter email and password';
      return;
    }
    
    isLoading = true;
    error = '';
    
    try {
      const { data, error: loginError } = await supabase.auth.signInWithPassword({
        email,
        password
      });
      
      if (loginError) {
        error = loginError.message;
      } else {
        goto('/');
      }
    } catch (err) {
      error = 'An unexpected error occurred';
    } finally {
      isLoading = false;
    }
  }
</script>

<svelte:head>
  <title>Login - FAIT</title>
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
        Sign in to FAIT
      </h2>
    </div>
    
    <form class="mt-8 space-y-6" on:submit|preventDefault={handleLogin}>
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="email" class="sr-only">Email address</label>
          <input
            id="email"
            name="email"
            type="email"
            bind:value={email}
            required
            class="relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            placeholder="Email address"
          />
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input
            id="password"
            name="password"
            type="password"
            bind:value={password}
            required
            class="relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            placeholder="Password"
          />
        </div>
      </div>
      
      {#if error}
        <div class="text-red-600 text-sm text-center">{error}</div>
      {/if}
      
      <div>
        <button
          type="submit"
          disabled={isLoading}
          class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50"
        >
          {#if isLoading}
            <LoadingSpinner size="small" color="white" />
          {:else}
            Sign in
          {/if}
        </button>
      </div>
      
      <div class="text-center text-sm text-gray-600">
        Demo: admin@fait.com / admin123
      </div>
    </form>
  </div>
</div>

// fait-mono/apps/fait-coop/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import Button from '../components/ui/Button.vue'
import MainLayout from '../components/layout/MainLayout.vue'

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()

// Form data
const email = ref('')
const password = ref('')
const rememberMe = ref(false)
const formError = ref('')
const isSubmitting = ref(false)

// Handle form submission
const handleSubmit = async () => {
  // Reset error
  formError.value = ''

  // Validate form
  if (!email.value || !password.value) {
    formError.value = 'Please enter both email and password'
    return
  }

  // Submit form
  isSubmitting.value = true
  try {
    const { success, error } = await auth.signIn(email.value, password.value)

    if (success) {
      // Redirect to dashboard or requested page
      const redirectPath = route.query.redirect?.toString() || '/dashboard'
      router.push(redirectPath)
    } else {
      formError.value = error || 'Invalid email or password'
    }
  } catch (err: any) {
    formError.value = err.message || 'An error occurred during login'
  } finally {
    isSubmitting.value = false
  }
}

// Navigate to register page
const navigateToRegister = () => {
  router.push('/register')
}
</script>

<template>
  <MainLayout>
    <div class="min-h-screen bg-neutral-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md">
      <h1 class="text-center text-3xl font-bold text-primary-600">FAIT Co-op</h1>
      <h2 class="mt-6 text-center text-2xl font-bold text-neutral-900">Sign in to your account</h2>
      <p class="mt-2 text-center text-sm text-neutral-600">
        Or
        <a @click="navigateToRegister" class="font-medium text-primary-600 hover:text-primary-500 cursor-pointer">
          create a new account
        </a>
      </p>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
      <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <!-- Error message -->
        <div v-if="formError" class="mb-4 p-3 bg-red-50 text-red-700 rounded-md text-sm">
          {{ formError }}
        </div>

        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Email field -->
          <div>
            <label for="email" class="block text-sm font-medium text-neutral-700">Email address</label>
            <div class="mt-1">
              <input
                id="email"
                v-model="email"
                name="email"
                type="email"
                autocomplete="email"
                required
                class="form-input"
              />
            </div>
          </div>

          <!-- Password field -->
          <div>
            <label for="password" class="block text-sm font-medium text-neutral-700">Password</label>
            <div class="mt-1">
              <input
                id="password"
                v-model="password"
                name="password"
                type="password"
                autocomplete="current-password"
                required
                class="form-input"
              />
            </div>
          </div>

          <!-- Remember me & Forgot password -->
          <div class="flex items-center justify-between">
            <div class="flex items-center">
              <input
                id="remember-me"
                v-model="rememberMe"
                name="remember-me"
                type="checkbox"
                class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-neutral-300 rounded"
              />
              <label for="remember-me" class="ml-2 block text-sm text-neutral-700">
                Remember me
              </label>
            </div>

            <div class="text-sm">
              <router-link to="/forgot-password" class="font-medium text-primary-600 hover:text-primary-500">
                Forgot your password?
              </router-link>
            </div>
          </div>

          <!-- Submit button -->
          <div>
            <Button
              type="submit"
              variant="primary"
              :loading="isSubmitting"
              :disabled="isSubmitting"
              fullWidth
            >
              Sign in
            </Button>
          </div>
        </form>
      </div>
    </div>
  </MainLayout>
</template>
