// fait-mono/apps/offershield/src/app/dashboard/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '../lib/supabase';

interface Analysis {
  id: string;
  created_at: string;
  job_type: string | null;
  confidence_score: number;
}

export default function DashboardPage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [analyses, setAnalyses] = useState<Analysis[]>([]);

  useEffect(() => {
    const checkUser = async () => {
      // For testing purposes, we'll create a mock user
      const mockUser = {
        id: '123',
        email: 'test@example.com'
      };

      setUser(mockUser);

      // For testing purposes, we'll create mock analyses
      const mockAnalyses = [
        {
          id: '1',
          created_at: new Date().toISOString(),
          job_type: 'Kitchen Remodel',
          confidence_score: 75
        },
        {
          id: '2',
          created_at: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
          job_type: 'Bathroom Renovation',
          confidence_score: 82
        },
        {
          id: '3',
          created_at: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
          job_type: 'Roofing',
          confidence_score: 68
        }
      ];

      setAnalyses(mockAnalyses);
      setLoading(false);

      // In production, you would use the following code:
      /*
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/auth');
        return;
      }

      setUser(user);

      // Fetch user's analyses
      const { data, error } = await supabase
        .from('analyses')
        .select('*')
        .order('created_at', { ascending: false });

      if (!error && data) {
        setAnalyses(data);
      }

      setLoading(false);
      */
    };

    checkUser();
  }, [router]);

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    router.push('/');
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow">
        <div className="container mx-auto px-6 py-4">
          <div className="flex justify-between items-center">
            <div className="text-2xl font-bold text-blue-600">OfferShield</div>
            <div className="flex items-center space-x-4">
              <span className="text-gray-700">
                {user?.email}
              </span>
              <button
                onClick={handleSignOut}
                className="text-gray-600 hover:text-gray-900"
              >
                Sign Out
              </button>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-8">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">Your Dashboard</h1>
          <Link
            href="/upload"
            className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors"
          >
            New Analysis
          </Link>
        </div>

        {analyses.length === 0 ? (
          <div className="bg-white rounded-lg shadow-md p-8 text-center">
            <h2 className="text-xl font-semibold mb-4">No analyses yet</h2>
            <p className="text-gray-600 mb-6">
              Upload your first contractor quote to get started with OfferShield.
            </p>
            <Link
              href="/upload"
              className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors"
            >
              Upload Quote
            </Link>
          </div>
        ) : (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {analyses.map((analysis) => (
              <div key={analysis.id} className="bg-white rounded-lg shadow-md overflow-hidden">
                <div className="p-6">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h3 className="font-semibold text-lg">
                        {analysis.job_type || 'Quote Analysis'}
                      </h3>
                      <p className="text-gray-500 text-sm">
                        {new Date(analysis.created_at).toLocaleDateString()}
                      </p>
                    </div>
                    <div className="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded">
                      {analysis.confidence_score}% Confidence
                    </div>
                  </div>
                  <Link
                    href={`/results/${analysis.id}`}
                    className="block w-full text-center bg-gray-100 hover:bg-gray-200 text-gray-800 font-medium py-2 px-4 rounded transition-colors"
                  >
                    View Analysis
                  </Link>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// src/routes/dashboard/+page.svelte
<script>
  import { supabase } from '$lib/supabase.js';
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  
  let user = null;
  let bookings = [];
  let isLoading = true;
  
  onMount(async () => {
    // Check authentication
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      goto('/login');
      return;
    }
    
    user = session.user;
    
    // Load user bookings (mock data for now)
    setTimeout(() => {
      bookings = [
        {
          id: 1,
          service: 'Handyman Services',
          provider: 'John Smith',
          date: '2024-01-15',
          time: '10:00 AM',
          status: 'confirmed',
          price: '$150'
        },
        {
          id: 2,
          service: 'Cleaning Services',
          provider: 'Clean Team Pro',
          date: '2024-01-20',
          time: '2:00 PM',
          status: 'pending',
          price: '$75'
        }
      ];
      isLoading = false;
    }, 1000);
  });
  
  function getStatusColor(status) {
    switch (status) {
      case 'confirmed': return 'bg-green-100 text-green-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'completed': return 'bg-blue-100 text-blue-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  }
</script>

<svelte:head>
  <title>Dashboard - FAIT</title>
</svelte:head>

<div class="container mx-auto px-4 py-8">
  <div class="max-w-6xl mx-auto">
    <!-- Welcome Section -->
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-800 mb-2">
        Welcome back{#if user}, {user.email.split('@')[0]}{/if}!
      </h1>
      <p class="text-gray-600">Manage your bookings and account settings</p>
    </div>
    
    <!-- Quick Actions -->
    <div class="grid md:grid-cols-4 gap-6 mb-8">
      <a href="/services" class="bg-blue-600 hover:bg-blue-700 text-white p-6 rounded-lg text-center transition-colors">
        <div class="text-3xl mb-2">🔍</div>
        <h3 class="font-semibold">Find Services</h3>
      </a>
      
      <a href="/bookings" class="bg-green-600 hover:bg-green-700 text-white p-6 rounded-lg text-center transition-colors">
        <div class="text-3xl mb-2">📅</div>
        <h3 class="font-semibold">My Bookings</h3>
      </a>
      
      <a href="/messages" class="bg-purple-600 hover:bg-purple-700 text-white p-6 rounded-lg text-center transition-colors">
        <div class="text-3xl mb-2">💬</div>
        <h3 class="font-semibold">Messages</h3>
      </a>
      
      <a href="/profile" class="bg-gray-600 hover:bg-gray-700 text-white p-6 rounded-lg text-center transition-colors">
        <div class="text-3xl mb-2">⚙️</div>
        <h3 class="font-semibold">Settings</h3>
      </a>
    </div>
    
    <!-- Recent Bookings -->
    <div class="bg-white rounded-lg shadow-lg p-6">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-2xl font-semibold text-gray-800">Recent Bookings</h2>
        <a href="/bookings" class="text-blue-600 hover:text-blue-700 font-medium">View All</a>
      </div>
      
      {#if isLoading}
        <div class="text-center py-8">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p class="mt-2 text-gray-600">Loading bookings...</p>
        </div>
      {:else if bookings.length > 0}
        <div class="space-y-4">
          {#each bookings as booking}
            <div class="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">
              <div class="flex justify-between items-start">
                <div>
                  <h3 class="font-semibold text-gray-800">{booking.service}</h3>
                  <p class="text-gray-600">Provider: {booking.provider}</p>
                  <p class="text-gray-600">{booking.date} at {booking.time}</p>
                </div>
                <div class="text-right">
                  <span class="inline-block px-3 py-1 rounded-full text-sm font-medium {getStatusColor(booking.status)}">
                    {booking.status.charAt(0).toUpperCase() + booking.status.slice(1)}
                  </span>
                  <p class="text-lg font-semibold text-gray-800 mt-1">{booking.price}</p>
                </div>
              </div>
            </div>
          {/each}
        </div>
      {:else}
        <div class="text-center py-8">
          <div class="text-4xl mb-4">📅</div>
          <h3 class="text-xl font-semibold text-gray-800 mb-2">No bookings yet</h3>
          <p class="text-gray-600 mb-4">Start by browsing our services and booking your first appointment.</p>
          <a href="/services" class="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded-lg">
            Browse Services
          </a>
        </div>
      {/if}
    </div>
  </div>
</div>
