// fait-mono/apps/fait-coop/src/views/NotFound.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import Button from '../components/ui/Button.vue'

const router = useRouter()

const goHome = () => {
  router.push('/')
}

const goBack = () => {
  router.back()
}
</script>

<template>
  <div class="min-h-screen bg-neutral-50 flex flex-col justify-center items-center px-4 py-12">
    <div class="text-center">
      <h1 class="text-9xl font-bold text-primary-600">404</h1>
      <h2 class="mt-4 text-3xl font-bold text-neutral-900">Page Not Found</h2>
      <p class="mt-2 text-lg text-neutral-600">
        The page you are looking for doesn't exist or has been moved.
      </p>
      <div class="mt-8 flex flex-col sm:flex-row justify-center gap-4">
        <Button @click="goHome" variant="primary">Go Home</Button>
        <Button @click="goBack" variant="outline">Go Back</Button>
      </div>
    </div>
  </div>
</template>

// src/components/NotFound.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const NotFound = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            404 - Page Not Found
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            The page you are looking for does not exist.
          </p>
        </div>
        <div className="mt-8 space-y-6">
          <div className="flex items-center justify-center">
            <Link
              to="/"
              className="group relative w-auto flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              Go back to home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NotFound;
