// FAIT 2.0/src/layouts/MainLayout.tsx
import React, { ReactNode } from 'react';
import Navbar from '../components/navigation/Navbar';
import DynamicFooter from '../components/animations/DynamicFooter';

interface MainLayoutProps {
  children: ReactNode;
  hideFooter?: boolean;
  transparentHeader?: boolean;
  className?: string;
}

const MainLayout: React.FC<MainLayoutProps> = ({
  children,
  hideFooter = false,
  transparentHeader = false,
  className = '',
}) => {
  return (
    <div className={`min-h-screen flex flex-col ${className}`}>
      <Navbar transparent={transparentHeader} />
      
      <main className="flex-grow">
        {children}
      </main>
      
      {!hideFooter && <DynamicFooter />}
    </div>
  );
};

export default MainLayout;

// fait-mono/apps/fait-coop/src/components/layout/MainLayout.vue
<script setup lang="ts">
import Navbar from './Navbar.vue'
import Footer from './Footer.vue'

defineProps({
  hideFooter: {
    type: Boolean,
    default: false
  }
})
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <Navbar />
    
    <main class="flex-grow">
      <slot></slot>
    </main>
    
    <Footer v-if="!hideFooter" />
  </div>
</template>
