// src/components/MainLayout.tsx
import React from 'react';
import CommonNavbar from './CommonNavbar';
import CommonFooter from './CommonFooter';

interface MainLayoutProps {
  children: React.ReactNode;
  currentPage?: string;
}

const MainLayout: React.FC<MainLayoutProps> = ({ children, currentPage = 'home' }) => {
  return (
    <div className="min-h-screen flex flex-col">
      <CommonNavbar currentPage={currentPage} />
      <main className="flex-grow">
        {children}
      </main>
      <CommonFooter />
    </div>
  );
};

export default MainLayout;

// fait-mono/apps/fait-coop/src/components/layout/MainLayout.vue
<script setup lang="ts">
import Navbar from './Navbar.vue'
import Footer from './Footer.vue'

defineProps({
  hideFooter: {
    type: Boolean,
    default: false
  }
})
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <Navbar />
    
    <main class="flex-grow">
      <slot></slot>
    </main>
    
    <Footer v-if="!hideFooter" />
  </div>
</template>
