// fait-mono/apps/offershield/src/app/components/Navbar.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { supabase } from '../lib/supabase';
import { useRouter } from 'next/navigation';

export default function Navbar() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      setLoading(false);
    };
    
    getUser();
    
    // Set up auth state change listener
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (event, session) => {
        setUser(session?.user || null);
      }
    );
    
    return () => {
      subscription.unsubscribe();
    };
  }, []);

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    router.push('/');
  };

  return (
    <nav className="bg-white shadow">
      <div className="container mx-auto px-6 py-4">
        <div className="flex justify-between items-center">
          <div>
            <Link href="/" className="text-2xl font-bold text-blue-600">
              OfferShield
            </Link>
          </div>
          
          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-6">
            <Link href="/#features" className="hover:text-blue-600">
              Features
            </Link>
            <Link href="/#how-it-works" className="hover:text-blue-600">
              How It Works
            </Link>
            <Link href="/#pricing" className="hover:text-blue-600">
              Pricing
            </Link>
            
            {loading ? (
              <div className="w-6 h-6 border-t-2 border-blue-500 border-solid rounded-full animate-spin"></div>
            ) : user ? (
              <div className="flex items-center space-x-4">
                <Link href="/dashboard" className="hover:text-blue-600">
                  Dashboard
                </Link>
                <button
                  onClick={handleSignOut}
                  className="text-gray-600 hover:text-gray-900"
                >
                  Sign Out
                </button>
              </div>
            ) : (
              <Link
                href="/auth"
                className="border border-blue-600 text-blue-600 px-4 py-2 rounded-lg hover:bg-blue-50 transition-colors"
              >
                Sign In
              </Link>
            )}
            
            <Link
              href="/upload"
              className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
            >
              Upload Quote
            </Link>
          </div>
          
          {/* Mobile Menu Button */}
          <div className="md:hidden">
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="text-gray-600 hover:text-gray-900 focus:outline-none"
            >
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                {mobileMenuOpen ? (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                ) : (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                )}
              </svg>
            </button>
          </div>
        </div>
        
        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden mt-4 pt-4 border-t border-gray-200">
            <div className="flex flex-col space-y-4">
              <Link href="/#features" className="hover:text-blue-600">
                Features
              </Link>
              <Link href="/#how-it-works" className="hover:text-blue-600">
                How It Works
              </Link>
              <Link href="/#pricing" className="hover:text-blue-600">
                Pricing
              </Link>
              
              {user ? (
                <>
                  <Link href="/dashboard" className="hover:text-blue-600">
                    Dashboard
                  </Link>
                  <button
                    onClick={handleSignOut}
                    className="text-left text-gray-600 hover:text-gray-900"
                  >
                    Sign Out
                  </button>
                </>
              ) : (
                <Link
                  href="/auth"
                  className="border border-blue-600 text-blue-600 px-4 py-2 rounded-lg hover:bg-blue-50 transition-colors inline-block"
                >
                  Sign In
                </Link>
              )}
              
              <Link
                href="/upload"
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors inline-block"
              >
                Upload Quote
              </Link>
            </div>
          </div>
        )}
      </div>
    </nav>
  );
}

// fait-mono/apps/fait-coop/src/components/layout/Navbar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import Button from '../ui/Button.vue'
import Avatar from '../ui/Avatar.vue'

const auth = useAuthStore()
const router = useRouter()
const isMenuOpen = ref(false)
const isToolsMenuOpen = ref(false)

// Toggle mobile menu
const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

// Toggle tools menu on mobile
const toggleToolsMenu = () => {
  isToolsMenuOpen.value = !isToolsMenuOpen.value
}

// Close mobile menu
const closeMenu = () => {
  isMenuOpen.value = false
  isToolsMenuOpen.value = false
}

// Navigate to login page
const navigateToLogin = () => {
  closeMenu()
  router.push('/login')
}

// Navigate to register page
const navigateToRegister = () => {
  closeMenu()
  router.push('/register')
}

// Navigate to dashboard
const navigateToDashboard = () => {
  closeMenu()
  router.push('/dashboard')
}

// Handle sign out
const handleSignOut = async () => {
  await auth.signOut()
  router.push('/')
  closeMenu()
}

// User display name
const userDisplayName = computed(() => {
  if (!auth.user) return ''
  return auth.user.full_name || auth.user.email
})

// User initials
const userInitials = computed(() => {
  if (!auth.user) return ''
  if (auth.user.full_name) {
    return auth.user.full_name
      .split(' ')
      .map(word => word[0])
      .slice(0, 2)
      .join('')
      .toUpperCase()
  }
  return auth.user.email.substring(0, 2).toUpperCase()
})
</script>

<template>
  <header class="bg-white shadow-sm">
    <div class="container-wide py-4 flex items-center justify-between">
      <div class="flex items-center">
        <router-link to="/" class="flex items-center" @click="closeMenu">
          <h1 class="text-2xl font-bold text-primary-600">FAIT Co-op</h1>
        </router-link>
      </div>

      <!-- Desktop Navigation -->
      <nav class="hidden md:flex items-center space-x-4">
        <router-link to="/" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Home</router-link>
        <router-link to="/about" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">About</router-link>
        <router-link to="/services" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Services</router-link>
        <router-link to="/community" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Community</router-link>
        <router-link to="/goodfait" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">GoodFAIT</router-link>
        <router-link to="/contact" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Contact</router-link>

        <!-- Tools Dropdown -->
        <div class="relative group">
          <button class="flex items-center space-x-1 text-neutral-700 hover:text-primary-600 transition-colors duration-200 focus:outline-none">
            <span>Tools</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-neutral-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div class="absolute left-0 mt-2 w-56 bg-white rounded-md shadow-lg py-1 z-10 hidden group-hover:block">
            <a href="https://offer.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              OfferShield - Quote Risk Analyzer
            </a>
            <a href="https://score.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Home Health Score
            </a>
            <a href="https://handy.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Handyman Calculator
            </a>
            <a href="https://flipper.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              FlipperCalc - House Flipping Budget
            </a>
            <a href="https://remodel.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Remodeling Calculator
            </a>
          </div>
        </div>

        <div v-if="auth.isAuthenticated" class="flex items-center space-x-4">
          <Button @click="navigateToDashboard" variant="primary" size="sm">Dashboard</Button>
          <div class="relative group">
            <button class="flex items-center space-x-2 focus:outline-none">
              <Avatar :initials="userInitials" size="sm" />
              <span class="text-sm font-medium text-neutral-700">{{ userDisplayName }}</span>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-neutral-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
            <div class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-10 hidden group-hover:block">
              <router-link to="/profile" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Profile</router-link>
              <router-link to="/settings" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Settings</router-link>
              <button @click="handleSignOut" class="block w-full text-left px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Sign Out</button>
            </div>
          </div>
        </div>
        <div v-else class="flex space-x-2">
          <Button @click="navigateToLogin" variant="outline" size="sm">Login</Button>
          <Button @click="navigateToRegister" variant="primary" size="sm">Register</Button>
        </div>
      </nav>

      <!-- Mobile Menu Button -->
      <button @click="toggleMenu" class="md:hidden p-2 rounded-md text-neutral-400 hover:text-neutral-500 hover:bg-neutral-100 focus:outline-none">
        <svg v-if="!isMenuOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Mobile Menu -->
    <div v-if="isMenuOpen" class="md:hidden bg-white border-t border-neutral-200 py-2">
      <div class="container-wide space-y-1">
        <router-link to="/" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Home</router-link>
        <router-link to="/about" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">About</router-link>
        <router-link to="/services" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Services</router-link>
        <router-link to="/community" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Community</router-link>
        <router-link to="/goodfait" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">GoodFAIT</router-link>
        <router-link to="/contact" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Contact</router-link>

        <!-- Tools Dropdown for Mobile -->
        <div>
          <button @click="toggleToolsMenu" class="flex w-full justify-between items-center px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50 focus:outline-none">
            <span>Tools</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path v-if="isToolsMenuOpen" fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd" />
              <path v-else fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div v-if="isToolsMenuOpen" class="pl-4 space-y-1">
            <a href="https://offer.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              OfferShield - Quote Risk Analyzer
            </a>
            <a href="https://score.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Home Health Score
            </a>
            <a href="https://handy.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Handyman Calculator
            </a>
            <a href="https://flipper.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              FlipperCalc - House Flipping Budget
            </a>
            <a href="https://remodel.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Remodeling Calculator
            </a>
          </div>
        </div>

        <div v-if="auth.isAuthenticated" class="pt-4 pb-3 border-t border-neutral-200">
          <div class="flex items-center px-3">
            <div class="flex-shrink-0">
              <Avatar :initials="userInitials" size="md" />
            </div>
            <div class="ml-3">
              <div class="text-base font-medium text-neutral-800">{{ userDisplayName }}</div>
              <div class="text-sm font-medium text-neutral-500">{{ auth.user?.email }}</div>
            </div>
          </div>
          <div class="mt-3 space-y-1">
            <router-link to="/dashboard" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Dashboard</router-link>
            <router-link to="/profile" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Profile</router-link>
            <router-link to="/settings" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Settings</router-link>
            <button @click="handleSignOut" class="block w-full text-left px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Sign Out</button>
          </div>
        </div>
        <div v-else class="pt-4 pb-3 border-t border-neutral-200">
          <div class="flex flex-col space-y-2 px-3">
            <Button @click="navigateToLogin" variant="outline" fullWidth>Login</Button>
            <Button @click="navigateToRegister" variant="primary" fullWidth>Register</Button>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<style scoped>
/* Transition for mobile menu */
.mobile-menu-enter-active,
.mobile-menu-leave-active {
  transition: opacity 0.3s, transform 0.3s;
}

.mobile-menu-enter-from,
.mobile-menu-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
