// FAIT 2.0/src/components/navigation/Navbar.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X } from 'lucide-react';
import Button from '../ui/Button';

interface NavbarProps {
  transparent?: boolean;
}

const Navbar: React.FC<NavbarProps> = ({ transparent = false }) => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const location = useLocation();
  
  // Navigation items
  const navItems = [
    { name: 'Home', path: '/' },
    { name: 'About', path: '/about' },
    { name: 'Services', path: '/services' },
    { name: 'Pricing', path: '/pricing' },
    { name: 'Contact', path: '/contact' },
  ];
  
  // Handle scroll effect
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 10) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };
    
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);
  
  // Close mobile menu when route changes
  useEffect(() => {
    setIsMobileMenuOpen(false);
  }, [location.pathname]);
  
  // Determine navbar background
  const navbarClasses = transparent && !isScrolled
    ? 'bg-transparent text-white'
    : 'bg-white text-neutral-800 shadow-sm';
  
  return (
    <>
      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${navbarClasses}`}>
        <div className="container-wide py-4">
          <div className="flex items-center justify-between">
            {/* Logo */}
            <Link to="/" className="flex items-center">
              <img 
                src="/images/logo.svg" 
                alt="FAIT Co-op" 
                className="h-8 w-auto" 
              />
            </Link>
            
            {/* Desktop Navigation */}
            <div className="hidden md:flex items-center space-x-8">
              {navItems.map((item) => (
                <Link
                  key={item.path}
                  to={item.path}
                  className={`font-medium hover:text-primary-600 transition-colors ${
                    location.pathname === item.path ? 'text-primary-600' : 'text-current'
                  }`}
                >
                  {item.name}
                </Link>
              ))}
            </div>
            
            {/* CTA Buttons */}
            <div className="hidden md:flex items-center space-x-4">
              <Button as={Link} to="/login" variant="ghost">
                Sign In
              </Button>
              <Button as={Link} to="/register">
                Join Now
              </Button>
            </div>
            
            {/* Mobile Menu Button */}
            <button
              className="md:hidden p-2 rounded-md"
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            >
              {isMobileMenuOpen ? (
                <X className="h-6 w-6" />
              ) : (
                <Menu className="h-6 w-6" />
              )}
            </button>
          </div>
        </div>
      </nav>
      
      {/* Mobile Menu */}
      <AnimatePresence>
        {isMobileMenuOpen && (
          <motion.div
            className="fixed inset-0 z-40 bg-white pt-16"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.2 }}
          >
            <div className="container mx-auto px-4 py-8">
              <div className="flex flex-col space-y-6">
                {navItems.map((item) => (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={`text-xl font-medium ${
                      location.pathname === item.path ? 'text-primary-600' : 'text-neutral-800'
                    }`}
                  >
                    {item.name}
                  </Link>
                ))}
                
                <div className="pt-6 border-t border-neutral-100 flex flex-col space-y-4">
                  <Button as={Link} to="/login" variant="outline" fullWidth>
                    Sign In
                  </Button>
                  <Button as={Link} to="/register" fullWidth>
                    Join Now
                  </Button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      
      {/* Spacer for fixed navbar */}
      <div className="h-16" />
    </>
  );
};

export default Navbar;

// fait-mono/apps/fait-coop/src/components/layout/Navbar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import Button from '../ui/Button.vue'
import Avatar from '../ui/Avatar.vue'

const auth = useAuthStore()
const router = useRouter()
const isMenuOpen = ref(false)
const isToolsMenuOpen = ref(false)

// Toggle mobile menu
const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

// Toggle tools menu on mobile
const toggleToolsMenu = () => {
  isToolsMenuOpen.value = !isToolsMenuOpen.value
}

// Close mobile menu
const closeMenu = () => {
  isMenuOpen.value = false
  isToolsMenuOpen.value = false
}

// Navigate to login page
const navigateToLogin = () => {
  closeMenu()
  router.push('/login')
}

// Navigate to register page
const navigateToRegister = () => {
  closeMenu()
  router.push('/register')
}

// Navigate to dashboard
const navigateToDashboard = () => {
  closeMenu()
  router.push('/dashboard')
}

// Handle sign out
const handleSignOut = async () => {
  await auth.signOut()
  router.push('/')
  closeMenu()
}

// User display name
const userDisplayName = computed(() => {
  if (!auth.user) return ''
  return auth.user.full_name || auth.user.email
})

// User initials
const userInitials = computed(() => {
  if (!auth.user) return ''
  if (auth.user.full_name) {
    return auth.user.full_name
      .split(' ')
      .map(word => word[0])
      .slice(0, 2)
      .join('')
      .toUpperCase()
  }
  return auth.user.email.substring(0, 2).toUpperCase()
})
</script>

<template>
  <header class="bg-white shadow-sm">
    <div class="container-wide py-4 flex items-center justify-between">
      <div class="flex items-center">
        <router-link to="/" class="flex items-center" @click="closeMenu">
          <h1 class="text-2xl font-bold text-primary-600">FAIT Co-op</h1>
        </router-link>
      </div>

      <!-- Desktop Navigation -->
      <nav class="hidden md:flex items-center space-x-4">
        <router-link to="/" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Home</router-link>
        <router-link to="/about" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">About</router-link>
        <router-link to="/services" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Services</router-link>
        <router-link to="/community" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Community</router-link>
        <router-link to="/goodfait" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">GoodFAIT</router-link>
        <router-link to="/contact" class="text-neutral-700 hover:text-primary-600 transition-colors duration-200">Contact</router-link>

        <!-- Tools Dropdown -->
        <div class="relative group">
          <button class="flex items-center space-x-1 text-neutral-700 hover:text-primary-600 transition-colors duration-200 focus:outline-none">
            <span>Tools</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-neutral-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div class="absolute left-0 mt-2 w-56 bg-white rounded-md shadow-lg py-1 z-10 hidden group-hover:block">
            <a href="https://offer.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              OfferShield - Quote Risk Analyzer
            </a>
            <a href="https://score.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Home Health Score
            </a>
            <a href="https://handy.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Handyman Calculator
            </a>
            <a href="https://flipper.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              FlipperCalc - House Flipping Budget
            </a>
            <a href="https://remodel.fait.coop" target="_blank" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">
              Remodeling Calculator
            </a>
          </div>
        </div>

        <div v-if="auth.isAuthenticated" class="flex items-center space-x-4">
          <Button @click="navigateToDashboard" variant="primary" size="sm">Dashboard</Button>
          <div class="relative group">
            <button class="flex items-center space-x-2 focus:outline-none">
              <Avatar :initials="userInitials" size="sm" />
              <span class="text-sm font-medium text-neutral-700">{{ userDisplayName }}</span>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-neutral-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
            <div class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-10 hidden group-hover:block">
              <router-link to="/profile" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Profile</router-link>
              <router-link to="/settings" class="block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Settings</router-link>
              <button @click="handleSignOut" class="block w-full text-left px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100">Sign Out</button>
            </div>
          </div>
        </div>
        <div v-else class="flex space-x-2">
          <Button @click="navigateToLogin" variant="outline" size="sm">Login</Button>
          <Button @click="navigateToRegister" variant="primary" size="sm">Register</Button>
        </div>
      </nav>

      <!-- Mobile Menu Button -->
      <button @click="toggleMenu" class="md:hidden p-2 rounded-md text-neutral-400 hover:text-neutral-500 hover:bg-neutral-100 focus:outline-none">
        <svg v-if="!isMenuOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Mobile Menu -->
    <div v-if="isMenuOpen" class="md:hidden bg-white border-t border-neutral-200 py-2">
      <div class="container-wide space-y-1">
        <router-link to="/" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Home</router-link>
        <router-link to="/about" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">About</router-link>
        <router-link to="/services" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Services</router-link>
        <router-link to="/community" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Community</router-link>
        <router-link to="/goodfait" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">GoodFAIT</router-link>
        <router-link to="/contact" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Contact</router-link>

        <!-- Tools Dropdown for Mobile -->
        <div>
          <button @click="toggleToolsMenu" class="flex w-full justify-between items-center px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50 focus:outline-none">
            <span>Tools</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path v-if="isToolsMenuOpen" fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd" />
              <path v-else fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div v-if="isToolsMenuOpen" class="pl-4 space-y-1">
            <a href="https://offer.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              OfferShield - Quote Risk Analyzer
            </a>
            <a href="https://score.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Home Health Score
            </a>
            <a href="https://handy.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Handyman Calculator
            </a>
            <a href="https://flipper.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              FlipperCalc - House Flipping Budget
            </a>
            <a href="https://remodel.fait.coop" target="_blank" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">
              Remodeling Calculator
            </a>
          </div>
        </div>

        <div v-if="auth.isAuthenticated" class="pt-4 pb-3 border-t border-neutral-200">
          <div class="flex items-center px-3">
            <div class="flex-shrink-0">
              <Avatar :initials="userInitials" size="md" />
            </div>
            <div class="ml-3">
              <div class="text-base font-medium text-neutral-800">{{ userDisplayName }}</div>
              <div class="text-sm font-medium text-neutral-500">{{ auth.user?.email }}</div>
            </div>
          </div>
          <div class="mt-3 space-y-1">
            <router-link to="/dashboard" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Dashboard</router-link>
            <router-link to="/profile" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Profile</router-link>
            <router-link to="/settings" @click="closeMenu" class="block px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Settings</router-link>
            <button @click="handleSignOut" class="block w-full text-left px-3 py-2 rounded-md text-base font-medium text-neutral-700 hover:text-primary-600 hover:bg-neutral-50">Sign Out</button>
          </div>
        </div>
        <div v-else class="pt-4 pb-3 border-t border-neutral-200">
          <div class="flex flex-col space-y-2 px-3">
            <Button @click="navigateToLogin" variant="outline" fullWidth>Login</Button>
            <Button @click="navigateToRegister" variant="primary" fullWidth>Register</Button>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<style scoped>
/* Transition for mobile menu */
.mobile-menu-enter-active,
.mobile-menu-leave-active {
  transition: opacity 0.3s, transform 0.3s;
}

.mobile-menu-enter-from,
.mobile-menu-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
